package entidades;
// Generated 8/08/2013 11:46:49 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.validation.constraints.Max;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String apellido;
     private String edad;
     private String telefono;
     private Date fechaNacimiento;

    public Persona() {
    }

	
    public Persona(String nombre, String apellido, Date fechaNacimiento) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.fechaNacimiento = fechaNacimiento;
    }
    public Persona(String nombre, String apellido, String edad, String telefono, Date fechaNacimiento) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.edad = edad;
       this.telefono = telefono;
       this.fechaNacimiento = fechaNacimiento;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getEdad() {
        return this.edad;
    }
    
    public void setEdad(String edad) {
        this.edad = edad;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }




}


